web/app/__init__.py
import os
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_flatpages import FlatPages
from config import Config

bootstrap = Bootstrap()
pages = FlatPages()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    app.config['GITHUB_SECRET'] = os.environ.get('GITHUB_SECRET')
    app.config['REPO_PATH'] = os.environ.get('REPO_PATH')

    bootstrap.init_app(app)
    pages.init_app(app)

    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.blog import bp as blog_bp
    app.register_blueprint(blog_bp)

    from app.image_search import bp as image_search_bp
    app.register_blueprint(image_search_bp)

    return app

web/app/blog/__init__.py
from flask import Blueprint

bp = Blueprint('blog', __name__)

from app.blog import routes

web/app/blog/routes.py
from flask import render_template
from app.blog import bp
from flask import current_app
from app import pages 
from flask_flatpages import pygments_style_defs

@bp.route('/blog/<string:page_name>/')
def render_static(page_name):
    post_dir = current_app.config['POST_DIR']
    path = "{}/{}".format(post_dir, page_name)
    post = pages.get_or_404(path)
    return render_template("page.html", post=post)

@bp.route('/pygments.css')
def pygments_css():
    return pygments_style_defs('default'), 200, {'Content-Type': 'text/css'}

web/app/image_search/__init__.py
from flask import Blueprint

bp = Blueprint('image_search', __name__)

from app.image_search import routes
from app.image_search import helpers 
from app.image_search import settings 

web/app/image_search/routes.py
from flask import render_template
from app.image_search import bp
from flask import current_app

from PIL import Image
import numpy as np
import flask
import redis
import uuid
import time
import json
import io
import cv2

from app.image_search import settings
from app.image_search import helpers 

redis_db = redis.StrictRedis(host=settings.REDIS_HOST, port=settings.REDIS_PORT, db=settings.REDIS_DB)

def standardize(image, mean, std):
    if image.ndim < 3:
        raise ValueError(
            f"Expected tensor to be a tensor image of size (..., C, H, W). Got tensor.size() = {image.size()}"
        )

    image = cv2.resize(
        src = image, 
        dsize = (224, 224), 
        interpolation = cv2.INTER_CUBIC
    )

    image = image.astype(float) / 255
    image = np.asarray(image, dtype='float32')

    mean = np.asarray(mean, dtype='float32')
    std = np.asarray(std, dtype='float32')

    if (mean.ndim == 1):
        mean = np.reshape(mean, (1, 1, -1))

    if (std.ndim == 1):
        std = np.reshape(std, (1, 1, -1))

    standardized_img = np.divide(np.subtract(image, mean), std)

    # return with channels first ordering
    return np.moveaxis(standardized_img, 2, 0)

@bp.route('/predict', methods=["GET", "POST"])
def predict():
 # initialize the data dictionary that will be returned from the view
    data = {"success": False}

    # ensure an image was properly uploaded to our endpoint
    if flask.request.method == "POST":
        print("at try", flush=True)
        try:
            print("file posted")
            if "image" in flask.request.files:
            #if flask.request.files.get("file"):
                print("image detected", flush=True)
                # read the image in PIL format and prepare it for classification
                image = flask.request.files["image"].read()
                image = Image.open(io.BytesIO(image))
                image = standardize(
                    image = np.asarray(image), 
                    mean = [0.485, 0.456, 0.406], 
                    std = [0.229, 0.224, 0.225]
                )

                # check that image shape is correct 
                print("image shape: {}".format(image.shape), flush=True)
                assert image.shape == (3, 224, 224)

                # ensure our NumPy array is C-contiguous as well,
                # otherwise we won't be able to serialize it
                image = image.copy(order="C")

                # generate an ID for the classification then add the
                # classification ID + image to the queue
                k = str(uuid.uuid4())
                d = {"id": k, "image": helpers.base64_encode_image(image)}
                redis_db.rpush(settings.IMAGE_QUEUE, json.dumps(d))

                # keep looping until our model server returns the output
                # predictions
                while True:
                    # attempt to grab the output predictions (similar image paths)
                    output = redis_db.get(k)

                    # check to see if our model has classified the input image
                    if output is not None:
                        # add the output predictions to our data
                        # dictionary so we can return it to the client
                        output = output.decode("utf-8")
                        data["paths"] = json.loads(output)

                        # delete the result from the database and break from the polling loop
                        redis_db.delete(k)
                        break

                    # sleep for a small amount to give the model a chance
                    # to classify the input image
                    time.sleep(settings.CLIENT_SLEEP)

                # indicate that the request was a success
                data["success"] = True

            # return the data dictionary as a JSON response
            if data["success"] == True:
                # rework paths
                paths = []
                for path in data["paths"]:
                    p = path.split("/")
                    s = p[-3] + "/" + p[-2] + "/" + p[-1]
                    paths.append(s)
                print(paths, flush=True)
                return render_template("predict.html", files=paths, message="Here are the most similar images found!")
            else:
                return render_template("predict.html", files="", message="There was an error!")
        except:
            redis_db.flushall()
            return render_template("predict.html", files="", message="There was an error! RGB images should be uploaded. Anything else (svg, grayscale) will result in an error.")

    elif flask.request.method == "GET":
        return render_template("predict.html", files="")

    

web/app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes 

web/app/main/routes.py
from datetime import datetime 
import time 
from flask import render_template, flash, redirect, url_for, request, g, \
    jsonify, current_app
from app import pages 
from app.main import bp 

def date_to_int(date):
    date = time.mktime(date.timetuple())
    return date  

@bp.route('/')
@bp.route('/index')
def index():
    return render_template('index.html')

@bp.route('/blog')
def blog():
    posts = [ p for p in pages if p.path.startswith(current_app.config['POST_DIR']) ]
    posts.sort(key=lambda item:date_to_int(item['date']), reverse=True)
    return render_template('blog.html', posts=posts)

@bp.route('/resume')
def resume():
    return render_template('resume.html')

@bp.route('/about')
def about():
    return render_template('about.html')

@bp.route('/projects')
def projects():
    return render_template('projects.html')






    

web/app/templates/_post.html
<div class="post-head">
    <i class="right"></i>
    <a href="{{ url_for('blog.render_static', page_name=post.link.replace(".html", "")) }}"><h2 class="post-title">{{ post.title }}</h2></a>
    <p class="post-date">{{ post.date }}</p>
</div>

web/app/templates/about.html
{% extends "base.html" %}

{% block app_content %}
    <div class="row">
        <div class="col-12">
            <!-- <h3><strong>Jacob</strong> Senecal</h3> -->
            <img class="col-6" src="{{ url_for('static', filename="img/about_pic.jpg") }}">
            <p>
            I am currently a software engineer at Figure Technologies. Figure is a financial 
            technology company leveraging blockchain, AI and analytics to deliver products to 
            improve the financial lives of our customers. We create innovative products for 
            consumers and a blockchain protocol that enhances the origination, custody, trading 
            and securitization of assets for institutions.</p>
            
            <p>
            I completed my Bachelor's and Master's degrees at Montana State University in mechanical
            engineering and computer science respectively. During my graduate program I was a member of
            the Numerical Intelligent Systems Lab where we focus on applying machine learning, mathematics, 
            and software engineering to solve a variety of problems. My research focused on developing 
            techniques to assess the health of large volumes of fruits and vegetables using a combination 
            of hyper-spectral imaging and machine learning.</p>
            
            <p>
            In the past I have worked at Los Alamos National Laboratory, where I applied computational
            techniques to monitor the health of a variety of structures. I also spent
            time working in the computational fluid dynamics field developing new algorithms
            and visualizations.</p>
            
            <p>
            I also worked as an intern at Blackmore Sensors & Analytics (now part of Aurora), where I 
            developed software for automotive lidar systems.</p>
        </div>

        <!-- <div class="content col-4">
            <img style="max-width: 100%;" src="{{ url_for('static', filename="img/prof_pic_tall.jpg") }}">
        </div> -->
    </div>

    <div class="row news">
        <h3>News</h3>
        <div class="col-3">
            <span>May 13, 2019</span>
            <span>Jun 26, 2018</span>
            <span>Jun 1, 2018</span>
            <span>Aug 25, 2017</span>
            <span>Jan 7, 2017</span>
        </div>

        <div class="col-9">
            <span>First day at Figure Technologies</span>
            <span>Updated website launched!</span>
            <span>Started as intern at Blackmore Sensors & Analytics</span>
            <span>Began graduate school at Montana State.</span>
            <span>First day at Los Alamos National Laboratory</span>
        </div>
    </div>
{% endblock %}

web/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-111993378-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-111993378-1');
    </script>

    <!-- MathJax -->
    <script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-MML-AM_CHTML" async></script>
  
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Senecal Website">
    <meta name="author" content="Jacob Senecal">
    <meta name="keywords" content="machine, learning, blog, technology, data, science">
    <title>Jacob Senecal</title>
    <script defer src="https://use.fontawesome.com/releases/v5.8.1/js/all.js" integrity="sha384-g5uSoOSBd7KkhAMlnQILrecXvzst9TdC09/VM+pjDTCM+1il8RHz5fKANTFFb+gQ" crossorigin="anonymous"></script>
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> -->
    <link href="https://fonts.googleapis.com/css?family=Lato|Titillium+Web|Merriweather|Roboto+Mono|Baumans" rel="stylesheet"> 
    <!-- styles -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/timeline.css') }}">
    <link rel="stylesheet" href="{{ url_for('blog.pygments_css') }}">
  </head>

  <body>


    {% block navbar %}
        <div class="topnav container" id="myTopnav">
            <a href="{{ url_for('main.index') }}" class="home">
                 >$ cd /home/
                 <span class="logo_cursor"></span>
            </a>
            <a href="{{ url_for('main.resume') }}" class="nav-b">CV</a>
            <a href="{{ url_for('main.about') }}" class="nav-b">About</a>
            <a href="{{ url_for('main.blog') }}" class="nav-b">Blog</a>
            <a href="{{ url_for('main.projects') }}" class="nav-b">Projects</a>
            <a href="javascript:void(0);" class="icon" onclick="myFunction()">
                <i class="fa fa-bars"></i>
            </a>
        </div>
          
        <script>
            function myFunction() {
                var x = document.getElementById("myTopnav");
                if (x.className === "topnav") {
                    x.className += " responsive";
                } else {
                    x.className = "topnav";
                }
            }
        </script>
    {% endblock %}


    {% block content %}
    <div class="container">
        {# application content needs to be provided in the app_content block #}
        {% block app_content %}{% endblock %}
    </div>
    {% endblock %}

</body>
</html>

web/app/templates/blog.html
{% extends "base.html" %}

{% block app_content %}
    <h1 id="blog-header">Recent Posts</h1>

    <div style="margin-bottom: 30px;" class="col-12">
        {% for post in posts %}
            {% include '_post.html' %}
        {% endfor %}
    </div>

    

{% endblock %}

web/app/templates/index.html
{% extends "base.html" %}

{% block app_content %}

    <div class="col-12">
        <div class="about">
            <!-- <div class="avatar">
                <img src="{{ url_for('static', filename="img/prof_pic.jpg") }}">
            </div> -->

            <h1>Jacob Senecal</h1>
            <h2>Software Engineer</h2>

            <ul class="social_icons">
                <li><a target="_blank" href="https://github.com/senecal-jjs"><i class="fab fa-github"></i></a></li>
                <li> <a target="_blank" href="https://bitbucket.org/jsene/"><i class="fab fa-bitbucket"></i></a></li>
                <li><a target="_blank" href="https://www.linkedin.com/in/jacob-senecal-481552111/"><i class="fab fa-linkedin-in" aria-hidden="true"></i></a></li>
                <li><a target="_blank" href="mailto:senecaljacob@gmail.com"><i class="fas fa-envelope" aria-hidden="true"></i></a></li>
            </ul>
        </div>
    </div>

    <div class="col-12 footer"></div>


{% endblock %}

web/app/templates/page.html
{% extends "base.html" %}

{% block app_content %}

    <div class="content">
        <h2 class="post-title content-title">{{ post.title }}</h2>
        <p class="post-date">{{ post.date }}</p>
        
        {{ post.html|safe }}
    </div>

    
{% endblock %}

web/app/templates/predict.html
{% extends "base.html" %}

{% block app_content %}
<div class="content">
    <form action="{{ url_for('image_search.predict') }}" method="post" enctype="multipart/form-data">
        Select image to upload:
        <input type="file" name="image" id="fileToUpload" accept="image/*">
        <button style="padding:5px; border-radius:5px;" class="button" type="submit">Upload</button>
    </form>

    <p>Disclaimer: The backend code assumes that 3 band (RGB) images are being uploaded. If something else (grayscale, svg) is 
       uploaded you will receive an error message. 
    </p>

    <p>{{ message }}</p>
    {% for image in files %}
        <img class="img_predict" src="{{ url_for('static', filename=image) }}">
    {% endfor %}
</div>
{% endblock %}

web/app/templates/projects.html
{% extends "base.html" %}

{% block app_content %}
    <div class="img_row">
        <div class="col-5 card">
            <a href="{{ url_for('image_search.predict') }}">
            <h3>Image Similarity Search</h3>
            <p>Uses PyTorch to generate image embeddings, and performs
                fast nearest neighbor search by indexing the embeddings in 
                a KD-tree.
            </p>
            </a>
        </div>

        <div class="col-5 card">
            <a href="{{ url_for('blog.render_static', page_name="min") }}">
                <h3>MiniMax Tic-Tac-Toe</h3>
                <p>Play against a tic-tac-toe agent employing the minimax strategy.
                    The agent is written in javascript.
                </p>
            </a>
        </div>

        <div class="col-5 card">
            <a href="http://snowshoeanalytics.com">
                <h3>Identify Favorable Bets</h3>
                <p>React app that aggregates betting odds from multiple bookmakers
                    and identifies favorable opportunities.
                </p>
            </a>
        </div>
    </div>

{% endblock %}

web/app/templates/resume.html
{% extends "base.html" %}

{% block app_content %}
    
    <section class="intro">
        <div class="box">
            <h1>Find my full CV <a target="_blank" href="{{ url_for('static', filename="pdf/resume.pdf") }}">here</a></h1>
            <h3>Scroll down for an overview of my work history</h3>
        </div>
        </section>
        
        <section class="timeline">
        <ul>
            <li>
                <div>
                    <time>May 2019 - Present</time> 
                    <h3>Figure Technologies</h3>
                    Creating software in the financial technology world
                </div>
            </li>
            <li>
                <div>
                    <time>Aug 2017 - May 2019</time> 
                    <h3>Numerical Intelligent Systems Laboratory</h3>
                    Investigating machine learning techniques for hyperspectral imagery
                </div>
            </li>
            <li>
            <div>
                <time>June 2018 - May 2019</time> 
                <h3>Blackmore Sensors & Analytics</h3>
                Developing software for automotive LiDAR systems
            </div>
            </li>
            <li>
            <div>
                <time>Jan 2017 - Aug 2017</time> 
                <h3>Los Alamos National Laboratory</h3>
                Created data analysis and signal processing algorithms for a variety of sensor types
            </div>
            </li>
            <li>
            <div>
                <time>Jan 2015 - Dec 2016</time> 
                <h3>Fluids & Computations Laboratory</h3>
                Analyzed new algorithms for high fidelity multiphase flow simulations
            </div>
            </li>
            <li>
            <div>
                <time>Jun 2016 - Aug 2016</time> 
                <h3>Los Alamos National Laboratory</h3>
                Developed and verified a material damage model for qualification testing of mechanical components
            </div>
            </li>
            <li>
            <div>
                <time>Jan 2016 - Dec 2016</time> 
                <h3>AUVSI Robosub Competition</h3>
                Designed and constructed a robotic arm for an autonomous submarine
            </div>
            </li>
            <li>
            <div>
                <time>Aug 2014 - Dec 2016</time> 
                <h3>Engineers Without Borders</h3>
                Implemented a water supply and filtration system for a school of 500 students
            </div>
            </li>
        </ul>
    </section>

    <script>
        (function() {

            'use strict';

            // define variables
            var items = document.querySelectorAll(".timeline li");

            // check if an element is in viewport
            // http://stackoverflow.com/questions/123999/how-to-tell-if-a-dom-element-is-visible-in-the-current-viewport
            function isElementInViewport(el) {
            var rect = el.getBoundingClientRect();
            return (
                rect.top >= 0 &&
                rect.left >= 0 &&
                rect.bottom <= (window.innerHeight || document.documentElement.clientHeight) &&
                rect.right <= (window.innerWidth || document.documentElement.clientWidth)
            );
            }

            function callbackFunc() {
            for (var i = 0; i < items.length; i++) {
                if (isElementInViewport(items[i])) {
                items[i].classList.add("in-view");
                }
            }
            }

            // listen for events
            window.addEventListener("load", callbackFunc);
            window.addEventListener("resize", callbackFunc);
            window.addEventListener("scroll", callbackFunc);

            })();
    </script>
{% endblock %}